
   
tasks:
- init: |
    python3 -m venv /workspace/venv
    source /workspace/venv/bin/activate
    pushd /workspace
    zip -qr venv.zip venv
    rm -fr venv
    popd
  command: |
    pushd /workspace
    [ ! -d "/workspace/venv" ] && unzip -q venv.zip
    source /workspace/venv/bin/activate
    popd
ports:
  - port: 3000
    onOpen: open-browser